name: configure-iotr
version: '0.0.1'
summary: Configuration script for IOTR
description: |
 This script allows user to configure the IOTR from Itron. 
base: core
grade: stable
confinement: strict
architectures:
  - build-on: armhf
    run-on: armhf

apps:
  configure-iotr:
    command: bin/hello
    plugs: [home,network-bind]

parts:
  configure-iotr:
    plugin: python
    python-version: python3
    source: .
    stage-packages: [ncbi-blast+]
