name: iotr-configuration
version: '1.0.0'
summary: Configuration script for IOTR
description: |
 This script allows user to configure the IOTR from Itron. 
base: core
grade: devel
confinement: devmode
architectures:
  - build-on: armhf
    run-on: armhf 

apps:
  iotr-configuration:
    command: bin/iotr-configuration
    plugs: [home,network-bind,network,process-control,network-control,gsettings]

parts:
  iotr-configuration:
    plugin: python
    python-version: python3
    source: .
    stage-packages: [ncbi-blast+]
